author = "Charlotte Star"
title = "Meow"
description = "Charlotte's writings!"

# The URL the site will be built for
base_url = "/"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

feed_filenames = ["atom.xml", "rss.xml"]
generate_feeds = true

theme = "parchment"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[extra]
# Put all your custom variables here
